-- INSERT INTO user (username, password) VALUES ('asdf', 'asdf');
-- INSERT INTO user (username, password) VALUES ('sdfg', 'asdf');
-- INSERT INTO user (username, password) VALUES ('dfgh', 'asdf');
-- INSERT INTO user (username, password) VALUES ('fghj', 'asdf');
-- INSERT INTO user (username, password) VALUES ('ghjk', 'asdf');
-- INSERT INTO user (username, password) VALUES ('hjkl', 'asdf');
-- INSERT INTO user (username, password) VALUES ('qwer', 'asdf');
-- INSERT INTO user (username, password) VALUES ('wert', 'asdf');
-- INSERT INTO user (username, password) VALUES ('erty', 'asdf');
-- INSERT INTO user (username, password) VALUES ('rtyu', 'asdf');
-- INSERT INTO user (username, password) VALUES ('tyui', 'asdf');
-- INSERT INTO user (username, password) VALUES ('yuio', 'asdf');
-- INSERT INTO user (username, password) VALUES ('uiop', 'asdf');
-- INSERT INTO user (username, password) VALUES ('zxcv', 'asdf');
-- INSERT INTO user (username, password) VALUES ('xcvb', 'asdf');
-- INSERT INTO user (username, password) VALUES ('cvbn', 'asdf');
-- INSERT INTO user (username, password) VALUES ('vbnm', 'asdf');

INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('asdf', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('sdfg', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('dfgh', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('fghj', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('ghjk', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('hjkl', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('qwer', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('wert', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('erty', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('rtyu', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('tyui', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('yuio', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('uiop', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('zxcv', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('xcvb', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('cvbn', 'asdf', '123', false );
INSERT INTO book (bookname, authorname, ISBN, is_said ) VALUES ('vbnm', 'asdf', '123', false );

-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('三国演义', '罗贯中', '978-7-5364-8509-9');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('西游记', '吴承恩', '978-7-101-13000-3');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('水浒传', '施耐庵', '978-7-5364-8837-3');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('红楼梦', '曹雪芹', '978-7-101-13005-8');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('堂吉诃德', '塞万提斯', '978-7-5594-1263-8');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('双城记', '查尔斯·狄更斯', '978-7-5001-5086-2');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('魔戒', 'J·R·R·托尔金', '978-7-208-12165-2');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('小王子', '圣埃克苏佩里', '978-7-5364-8847-2');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('无人生还', '阿加莎·克里斯蒂', '978-7-5133-1292-9');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('霍比特人', 'J·R·R·托尔金', '978-7-208-14996-0');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('达·芬奇密码', '丹·布朗', '978-7-5321-5366-4');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('麦田里的守望者', 'J·D·塞林格', '978-7-5447-7511-3');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('家', '巴金', '978-7-5501-3658-8');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('春', '巴金', '978-7-02-014040-4');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('秋', '巴金', '978-7-02-011793-2');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('骆驼祥子', '老舍', '978-7-5392-9985-3');
-- INSERT INTO book (bookname, authorname, ISBN) VALUES ('阿Q正传', '鲁迅', '978-7-5470-4873-3');