INSERT INTO user (username, password) VALUES ('asdf', 'asdf');
INSERT INTO user (username, password) VALUES ('sdfg', 'asdf');
INSERT INTO user (username, password) VALUES ('dfgh', 'asdf');
INSERT INTO user (username, password) VALUES ('fghj', 'asdf');
INSERT INTO user (username, password) VALUES ('ghjk', 'asdf');
INSERT INTO user (username, password) VALUES ('hjkl', 'asdf');
INSERT INTO user (username, password) VALUES ('qwer', 'asdf');
INSERT INTO user (username, password) VALUES ('wert', 'asdf');
INSERT INTO user (username, password) VALUES ('erty', 'asdf');
INSERT INTO user (username, password) VALUES ('rtyu', 'asdf');
INSERT INTO user (username, password) VALUES ('tyui', 'asdf');
INSERT INTO user (username, password) VALUES ('yuio', 'asdf');
INSERT INTO user (username, password) VALUES ('uiop', 'asdf');
INSERT INTO user (username, password) VALUES ('zxcv', 'asdf');
INSERT INTO user (username, password) VALUES ('xcvb', 'asdf');
INSERT INTO user (username, password) VALUES ('cvbn', 'asdf');
INSERT INTO user (username, password) VALUES ('vbnm', 'asdf');

INSERT INTO book (bookName, authorName, ISBN) VALUES ('asdf', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('sdfg', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('dfgh', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('fghj', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('ghjk', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('hjkl', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('qwer', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('wert', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('erty', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('rtyu', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('tyui', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('yuio', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('uiop', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('zxcv', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('xcvb', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('cvbn', 'asdf', '123');
INSERT INTO book (bookName, authorName, ISBN) VALUES ('vbnm', 'asdf', '123');